title:            any2api
tagline:          'Auto-generate containerized APIs'
description:      'Auto-generate containerized APIs for any executable'
url:              http://any2api.org
baseurl:          /

author:
  name:           'Johannes Wettinger'
  url:            https://github.com/jojow

gems:
- 'jekyll-paginate'

permalink:        pretty
paginate:         3
paginate_path:    'page:num'

kramdown:
  input: GFM
  syntax_highlighter: rouge
