# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            any2api
tagline:          'Auto-generate containerized APIs'
description:      'Auto-generate containerized APIs for arbitrary executables'
url:              http://any2api.org
baseurl:          /

author:
  name:           'Johannes Wettinger'
  url:            https://github.com/jojow

paginate:         3
