title:            any2api
tagline:          'Auto-generate containerized APIs'
description:      'Auto-generate containerized APIs for arbitrary executables'
url:              http://any2api.org
baseurl:          /

author:
  name:           'Johannes Wettinger'
  url:            https://github.com/jojow

permalink:        pretty
paginate:         3
